#!/usr/bin/env python3
"""Verifica que o rice não saiu da paleta.

O RICE-GUIDE.md tem um não-negociável, "never invent a colour", que até agora
era regra de honra. Sete arquivos carregam hex colados à mão porque cor se
mistura com estrutura neles (swaylock, bottom, starship, fastfetch, fish, yazi,
e os papéis do Neovim), e nada avisava quando um deles envelhecia em relação ao
palette.json.

Duas verificações:

  drift    hex em config versionada que não existe no palette.json
  sync     arquivo GENERATED que difere do que o gerador produziria agora,
           o que acontece quando alguém edita a saída em vez da fonte

Uso:
    python3 scripts/theme/check_palette.py

Sai com código 1 se qualquer uma falhar, para poder entrar num hook depois.
"""
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import generate_theme as gen  # noqa: E402

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent

HEX = re.compile(r"#[0-9a-fA-F]{6}\b")

# Caminhos que não fazem parte do tema vivo. Os .legacy e os arquivos de tema
# antigo guardam de propósito as cores de antes; a paleta em si é a fonte, não
# um consumidor; e binários não têm cor para conferir.
SKIP_PARTS = (
    ".git/",
    ".legacy",
    "kanagawa",
    "flexoki",
    "lazy-lock.json",
    "fish_variables",
    "scripts/theme/palette.json",
    "dotfiles_backup",
)
SKIP_SUFFIX = (".png", ".jpg", ".jpeg", ".ttf", ".otf", ".woff", ".woff2", ".log", ".pyc")

# Exceções decididas, não esquecidas. O DESIGN-SYSTEM.md é o documento da
# vertente web, com escala própria, e não descreve o desktop. O dunstrc está
# órfão de propósito, guardado caso Jeff volte do swaync, e a decisão de não
# temizá-lo está registrada no CLAUDE.md. Um check que falha sempre deixa de
# ser lido, então exceção decidida sai da lista em vez de virar ruído.
SKIP_FILES = (
    "docs/design/DESIGN-SYSTEM.md",
    ".config/dunst/dunstrc",
)


def palette_colours(p: dict) -> set:
    known = set()
    for shades in p["scales"].values():
        known |= {v.lower() for v in shades.values()}
    for entry in p["alert"].values():
        known |= {v.lower() for v in entry.values()}
    known |= {v.lower() for v in p["ansi16"]}
    known.add(p["focus_ring"].lower())
    for value in p["terminal"].values():
        if isinstance(value, str) and value.startswith("#"):
            known.add(value.lower())
    return known


def check_drift(known: set) -> list:
    problems = []
    for path in sorted(REPO_ROOT.rglob("*")):
        rel = path.relative_to(REPO_ROOT).as_posix()
        if not path.is_file():
            continue
        if any(part in rel for part in SKIP_PARTS) or rel in SKIP_FILES:
            continue
        if path.suffix.lower() in SKIP_SUFFIX:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        # Arquivos gerados são conferidos pela verificação de sync, não aqui.
        if "GENERATED by scripts/theme" in text[:300]:
            continue
        stray = sorted({m.group(0).lower() for m in HEX.finditer(text)} - known)
        if stray:
            problems.append((rel, stray))
    return problems


def check_sync(p: dict) -> list:
    stale = []
    for path, expected in gen.generated_files(p).items():
        rel = path.relative_to(REPO_ROOT).as_posix()
        if not path.exists():
            stale.append((rel, "não existe"))
        elif path.read_text(encoding="utf-8") != expected:
            stale.append((rel, "difere do que o gerador produziria"))
    return stale


def main() -> int:
    p = gen.load_palette()
    known = palette_colours(p)
    failed = False

    drift = check_drift(known)
    if drift:
        failed = True
        print("Cores fora da paleta:\n")
        for rel, stray in drift:
            print(f"  {rel}")
            print(f"      {' '.join(stray)}")
        print()
    else:
        print(f"drift: nenhuma cor fora das {len(known)} da paleta")

    stale = check_sync(p)
    if stale:
        failed = True
        print("Arquivos gerados fora de sincronia (rode generate_theme.py):\n")
        for rel, why in stale:
            print(f"  {rel}: {why}")
        print()
    else:
        print(f"sync:  {len(gen.generated_files(p))} arquivos gerados conferem com palette.json")

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
