#!/usr/bin/env python3
"""Voidashi theme generator.

Reads palette.json (the single source of truth, transcribed from
docs/design/RICE-GUIDE.md and docs/design/DESIGN-SYSTEM.md) and writes the
color-only config partials each app natively includes. See RICE-GUIDE.md,
"Working rules".

The emitters here take two arguments: the palette, and the semantic layer that
roles.py builds from it. A colour decision belongs there and a toolkit's key
names belong here, which is the split that lets one decision reach GTK, Qt and
the terminals without being written three times.

Never hand-edit the files this script writes; they carry a GENERATED
header. Edit palette.json and rerun this script instead.
"""

import json
import re
from pathlib import Path

import roles

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
CONFIG = REPO_ROOT / ".config"

SOURCE_NOTE = "docs/design/RICE-GUIDE.md"

HEX_COLOUR = re.compile(r"#[0-9a-fA-F]{6}\Z")


# =====================================================================
#  Source and writing
# =====================================================================

def colour_keys(p: dict):
    """Every place in palette.json that must hold a colour, as (name, value).

    Written out rather than inferred, because the file also holds glyphs,
    geometry numbers and font names, and a walk that guessed which is which
    would have to guess again every time a key is added.

    Roles are not in here and cannot be. They live in roles.py and hold a
    colour this file already holds, which roles.validate() is what enforces.
    """
    for family, shades in p["scales"].items():
        for step, value in shades.items():
            yield f"scales.{family}.{step}", value
    for name, entry in p["alert"].items():
        for key in ("fg", "bg", "border"):
            yield f"alert.{name}.{key}", entry[key]
    for i, value in enumerate(p["ansi16"]):
        yield f"ansi16[{i}]", value


def validate_palette(p: dict) -> None:
    """Refuse a colour that is not #RRGGBB, here rather than downstream.

    Dropping the '#' from one value is a single keystroke and used to survive
    every check this repository has. check_sync compares the output against
    this generator, so a malformed input is "in sync" by construction, and
    check_drift's pattern needs the '#' to see the value at all. What shipped
    was a stylesheet GTK rejected with two parse errors, while both checks
    reported clean and the checker's palette count silently grew by one.
    """
    bad = [f"{name} = {value!r}" for name, value in colour_keys(p)
           if not isinstance(value, str) or not HEX_COLOUR.match(value)]
    if bad:
        raise SystemExit(
            "palette.json: these must be #RRGGBB and are not:\n  " + "\n  ".join(bad)
        )


def load_palette() -> dict:
    with open(SCRIPT_DIR / "palette.json", encoding="utf-8") as f:
        p = json.load(f)
    validate_palette(p)
    # Here rather than at each emitter, so that a broken semantic layer stops
    # the run instead of reaching one file and not another. check_palette.py
    # loads through this function too and inherits the check for free.
    roles.validate(p, roles.build(p))
    return p


def header(comment_start: str, comment_end: str = "") -> str:
    lines = [
        "GENERATED by scripts/theme/generate_theme.py from scripts/theme/palette.json",
        "Do not hand-edit: edit palette.json and rerun the generator.",
        f"Voidashi color scheme. See {SOURCE_NOTE}",
    ]
    return "\n".join(f"{comment_start} {line}{comment_end}" for line in lines) + "\n\n"


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(REPO_ROOT)}")


# =====================================================================
#  Terminals
# =====================================================================

def gen_kitty(p: dict, r: dict) -> str:
    a = p["ansi16"]
    # cursor_text_color is the text drawn underneath the cursor, which takes the
    # surface it sits on so the cursor reads as an inversion. Same in all four.
    out = header("#")
    out += f"background            {r['surface']['content']}\n"
    out += f"foreground            {r['text']['body']}\n"
    out += f"cursor                {r['identity']['cursor']}\n"
    out += f"cursor_text_color     {r['surface']['content']}\n"
    out += f"selection_background  {r['selection']['bg']}\n"
    out += f"selection_foreground  {r['selection']['fg']}\n\n"
    for i, hexval in enumerate(a):
        out += f"color{i:<2} {hexval}\n"
    return out


def gen_foot(p: dict, r: dict) -> str:
    a = p["ansi16"]
    strip = lambda h: h.lstrip("#")
    out = header("#")
    out += "[colors-dark]\n"
    out += f"background={strip(r['surface']['content'])}\n"
    out += f"foreground={strip(r['text']['body'])}\n"
    out += f"selection-foreground={strip(r['selection']['fg'])}\n"
    out += f"selection-background={strip(r['selection']['bg'])}\n"
    # [cursor].color was removed by foot. The replacement is a single "cursor"
    # key taking two colours, text first then background, which is why this is
    # written here rather than in a [cursor] section.
    out += f"cursor={strip(r['surface']['content'])} {strip(r['identity']['cursor'])}\n\n"
    for i in range(8):
        out += f"regular{i}={strip(a[i])}\n"
    out += "\n"
    for i in range(8):
        out += f"bright{i}={strip(a[8 + i])}\n"
    return out


def gen_ghostty(p: dict, r: dict) -> str:
    a = p["ansi16"]
    strip = lambda h: h.lstrip("#")
    out = header("#")
    out += f"background = {strip(r['surface']['content'])}\n"
    out += f"foreground = {strip(r['text']['body'])}\n"
    out += f"cursor-color = {strip(r['identity']['cursor'])}\n"
    out += f"cursor-text = {strip(r['surface']['content'])}\n"
    out += f"selection-background = {strip(r['selection']['bg'])}\n"
    out += f"selection-foreground = {strip(r['selection']['fg'])}\n\n"
    for i, hexval in enumerate(a):
        out += f"palette = {i}={hexval}\n"
    return out


def gen_alacritty(p: dict, r: dict) -> str:
    a = p["ansi16"]
    out = header("#")
    out += f"[colors.primary]\nbackground = '{r['surface']['content']}'\nforeground = '{r['text']['body']}'\n\n"
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    out += "[colors.normal]\n"
    for i, name in enumerate(names):
        out += f"{name} = '{a[i]}'\n"
    out += "\n[colors.bright]\n"
    for i, name in enumerate(names):
        out += f"{name} = '{a[8 + i]}'\n"
    out += f"\n[colors.cursor]\ntext = '{r['surface']['content']}'\ncursor = '{r['identity']['cursor']}'\n"
    out += f"\n[colors.selection]\nbackground = '{r['selection']['bg']}'\ntext = '{r['selection']['fg']}'\n"
    return out


# =====================================================================
#  Lua: Hyprland and Neovim
# =====================================================================

def gen_hypr_palette(p: dict) -> str:
    # Lua table keys that look like numbers ("00", "400") need bracket-string
    # form; only alpha keys like "deep" can be written bare.
    lua_key = lambda shade: shade if shade.isidentifier() else f'["{shade}"]'
    out = header("--")
    out += "return {\n"
    for scale_name, shades in p["scales"].items():
        out += f"    {scale_name} = {{\n"
        for shade, hexval in shades.items():
            out += f'        {lua_key(shade)} = "{hexval}",\n'
        out += "    },\n"
    out += "    alert = {\n"
    for name, entry in p["alert"].items():
        out += f'        {name} = {{ fg = "{entry["fg"]}", bg = "{entry["bg"]}", border = "{entry["border"]}" }},\n'
    out += "    },\n"
    g = p["geometry"]
    out += "    geometry = {\n"
    out += f'        radius_floating = {g["radius_floating"]},\n'
    out += f'        radius_docked = {g["radius_docked"]},\n'
    out += "    },\n"
    out += "}\n"
    return out


def gen_nvim_palette(p: dict) -> str:
    """Raw palette for the Neovim colorscheme, same shape as the Hyprland one.

    Only colours belong here. The semantic layer that turns them into roles
    lives beside it in roles.lua, hand-written, and the highlight groups read
    from that rather than from this file. Keeping the two apart is what lets the
    theme be recoloured without touching three hundred group definitions.
    """
    lua_key = lambda shade: shade if shade.isidentifier() else f'["{shade}"]'
    out = header("--")
    out += "return {\n"
    for scale_name, shades in p["scales"].items():
        out += f"    {scale_name} = {{\n"
        for shade, hexval in shades.items():
            out += f'        {lua_key(shade)} = "{hexval}",\n'
        out += "    },\n"
    out += "    alert = {\n"
    for name, entry in p["alert"].items():
        out += f'        {name} = {{ fg = "{entry["fg"]}", bg = "{entry["bg"]}", border = "{entry["border"]}" }},\n'
    out += "    },\n"
    # The ANSI table verbatim, so :terminal matches every other terminal and TUI
    # on the machine. That equivalence is a non-negotiable in RICE-GUIDE.md.
    out += "    ansi = {\n"
    for i, hexval in enumerate(p["ansi16"]):
        out += f'        [{i}] = "{hexval}",\n'
    out += "    },\n"
    out += "}\n"
    return out


# =====================================================================
#  GTK
# =====================================================================

BLOCK_START = "/* >>> VOIDASHI COLORS (GENERATED) >>> */"
BLOCK_END = "/* <<< END VOIDASHI COLORS <<< */"


def inlined_block(original: str, content: str, name: str) -> str:
    """Replace the marked block inside a hand-written CSS file.

    For apps that cannot @import the shared partial. wofi hands its stylesheet
    to GTK as a string, so relative @import urls resolve against the process's
    cwd (usually $HOME) instead of the file's directory, so the colors silently
    never load. Inlining sidesteps path resolution entirely. Everything outside
    the markers stays hand-written.
    """
    start = original.find(BLOCK_START)
    end = original.find(BLOCK_END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"{name}: missing the "
            f"{BLOCK_START} / {BLOCK_END} markers the generator writes between."
        )
    if end < start:
        # Without this the slice either side of the block re-emits the span
        # between the markers, so every run appends another copy of whatever
        # hand-written CSS sits between them, unbounded and without an error.
        raise SystemExit(
            f"{name}: {BLOCK_END} comes before "
            f"{BLOCK_START}; put them back in order."
        )
    block = f"{BLOCK_START}\n{content}{BLOCK_END}"
    return original[:start] + block + original[end + len(BLOCK_END):]


def gen_gtk_css(p: dict, r: dict) -> str:
    out = header("/*", " */")
    for scale_name, shades in p["scales"].items():
        for shade, hexval in shades.items():
            out += f"@define-color {scale_name}-{shade} {hexval};\n"
        out += "\n"
    for name, entry in p["alert"].items():
        out += f"@define-color alert-{name} {entry['fg']};\n"
        out += f"@define-color alert-{name}-bg {entry['bg']};\n"
        out += f"@define-color alert-{name}-border {entry['border']};\n"
    out += "\n"
    out += f"@define-color focus-ring {r['accent']['line']};\n"
    g = p["geometry"]
    out += (
        "\n/* Non-colour tokens, for reference. GTK3 (waybar, wofi, wlogout) has no\n"
        "   CSS custom properties, so these cannot be consumed as variables there the\n"
        "   way the colours above are: each GTK3 stylesheet carries the literal and\n"
        "   points back at palette.json. swaync is GTK4 and does read them.\n"
        f"     radius, floating surface: {g['radius_floating']}px\n"
        f"     radius, docked surface:   {g['radius_docked']}px\n"
        f"     UI font weight:           {g['font_weight_ui']} */\n"
    )
    return out


def gen_gtk_app_css(p: dict, r: dict, toolkit: str) -> str:
    """Named-colour overrides for ordinary GTK applications.

    Distinct from gen_gtk_css, which exports the raw palette for stylesheets we
    write ourselves. This one maps the semantic layer onto the names GTK and
    libadwaita already paint from, so applications nobody wrote a stylesheet for
    follow the desktop: pavucontrol, zenity, file choosers, network dialogs.

    What is decided here is which GTK name each role belongs to, and nothing
    else. Why a surface sits where it does is in roles.py, beside the role.
    """
    g = p["geometry"]
    surf, txt, ln = r["surface"], r["text"], r["line"]
    sel, acc, st = r["selection"], r["accent"], r["status"]
    out = header("/*", " */")
    out += f"/* {toolkit} named colours, mapped from palette.json */\n\n"

    if toolkit == "gtk4":
        pairs = [
            ("window_bg_color", surf["window"]),
            ("window_fg_color", txt["emphasis"]),
            ("view_bg_color", surf["content"]),
            ("view_fg_color", txt["emphasis"]),
            ("headerbar_bg_color", surf["raised"]),
            ("headerbar_fg_color", txt["emphasis"]),
            ("headerbar_border_color", ln["normal"]),
            ("headerbar_backdrop_color", surf["window"]),
            ("headerbar_shade_color", ln["dim"]),
            ("sidebar_bg_color", surf["window"]),
            ("sidebar_fg_color", txt["body"]),
            ("sidebar_border_color", ln["normal"]),
            ("sidebar_backdrop_color", surf["window"]),
            ("secondary_sidebar_bg_color", surf["window"]),
            ("secondary_sidebar_fg_color", txt["body"]),
            ("card_bg_color", surf["raised"]),
            ("card_fg_color", txt["emphasis"]),
            ("dialog_bg_color", surf["raised"]),
            ("dialog_fg_color", txt["emphasis"]),
            ("popover_bg_color", surf["raised"]),
            ("popover_fg_color", txt["emphasis"]),
            ("thumbnail_bg_color", surf["raised"]),
            ("thumbnail_fg_color", txt["emphasis"]),
            # The scrim behind a modal, which is the deepest surface there is.
            ("shade_color", surf["content"]),
            ("scrollbar_outline_color", ln["normal"]),
            ("accent_bg_color", sel["bg"]),
            ("accent_fg_color", sel["fg"]),
            ("accent_color", acc["line"]),
            # libadwaita spends four names on two tones: destructive is the
            # button, error is the message, and both are the critical tone.
            ("destructive_bg_color", st["critical"]["bg"]),
            ("destructive_fg_color", st["critical"]["fg"]),
            ("destructive_color", st["critical"]["fg"]),
            ("success_bg_color", st["good"]["bg"]),
            ("success_fg_color", st["good"]["fg"]),
            ("success_color", st["good"]["fg"]),
            ("warning_bg_color", st["caution"]["bg"]),
            ("warning_fg_color", st["caution"]["fg"]),
            ("warning_color", st["caution"]["fg"]),
            ("error_bg_color", st["critical"]["bg"]),
            ("error_fg_color", st["critical"]["fg"]),
            ("error_color", st["critical"]["fg"]),
            ("borders", ln["normal"]),
        ]
    else:
        pairs = [
            ("theme_bg_color", surf["window"]),
            ("theme_fg_color", txt["emphasis"]),
            ("theme_base_color", surf["content"]),
            ("theme_text_color", txt["emphasis"]),
            ("theme_selected_bg_color", sel["bg"]),
            ("theme_selected_fg_color", sel["fg"]),
            ("theme_unfocused_bg_color", surf["window"]),
            ("theme_unfocused_fg_color", txt["body"]),
            ("theme_unfocused_base_color", surf["content"]),
            ("theme_unfocused_text_color", txt["body"]),
            ("theme_unfocused_selected_bg_color", sel["bg_unfocused"]),
            ("theme_unfocused_selected_fg_color", sel["fg_unfocused"]),
            ("insensitive_bg_color", surf["raised"]),
            ("insensitive_fg_color", txt["disabled"]),
            ("insensitive_base_color", surf["window"]),
            ("borders", ln["normal"]),
            ("unfocused_borders", ln["dim"]),
            ("warning_color", st["caution"]["fg"]),
            ("error_color", st["critical"]["fg"]),
            ("success_color", st["good"]["fg"]),
            ("link_color", acc["line"]),
            ("visited_link_color", acc["visited"]),
        ]

    for name, hexval in pairs:
        out += f"@define-color {name} {hexval};\n"

    if toolkit == "gtk4":
        # GTK 4.16 moved this stylesheet onto CSS custom properties, and on
        # 4.22 the accent responds only to those: with @define-color
        # accent_bg_color set to one colour and --accent-bg-color to another in
        # the same file, the custom property is what renders. Surfaces still
        # honour @define-color, so both forms are emitted rather than guessing
        # which of the two any given GTK version reads.
        out += "\n:root {\n"
        for name, hexval in pairs:
            out += f"    --{name.replace('_', '-')}: {hexval};\n"
        out += "}\n"

    # Popovers, dialogs and menus float over other content, so they take the
    # floating radius; see RICE-GUIDE.md, "Form".
    r = g["radius_floating"]
    out += f"""
popover,
popover > contents,
menu,
.menu,
.context-menu,
tooltip,
tooltip.background,
messagedialog,
dialog {{
    border-radius: {r}px;
}}

/* Widgets that sit inside a surface stay square, matching the shell. */
button,
entry,
textview,
scrollbar,
notebook,
headerbar,
checkbutton check,
radiobutton radio {{
    border-radius: 0;
}}
"""
    return out


# =====================================================================
#  KDE
# =====================================================================

def kde_font(p: dict, size_key: str = "ui_size", mono: bool = False) -> str:
    """One font in the ten-field form KDE writes into kdeglobals.

    The fields are family, point size, pixel size, style hint, weight, italic,
    underline, strikeout, fixed pitch, raw mode. Only the first, second and
    fifth carry a decision; the rest are the defaults KDE itself writes.

    The weight is the Qt 0-99 scale, not the CSS one. Passing 500 there, which
    is what geometry.font_weight_ui holds, does not fail: it clamps and renders
    as Black. 57 is the Medium that 500 means.
    """
    t = p["typography"]
    family = t["mono_family"] if mono else t["ui_family"]
    weight = t["kde_weight_mono"] if mono else t["kde_weight"]
    return f"{family},{t[size_key]},-1,5,{weight},0,0,0,0,0"


def gen_kde_colors(p: dict) -> str:
    """KDE colour scheme, for the Qt half of the desktop.

    Nine KDE applications are installed (dolphin, ark, gwenview, kate,
    spectacle, and so on) and they read their colours from kdeglobals rather
    than from anything GTK. The format is INI with one block per role and
    values as "R,G,B" rather than hex.

    The blocks are not interchangeable: Window is the chrome, View is the
    content area a list or a text buffer draws on, Button is a raised control,
    Tooltip floats above everything. Mapping them all to one colour is what
    makes a Qt application look flat and wrong.
    """
    s, a = p["scales"], p["alert"]
    rgb = lambda h: ",".join(str(int(h.lstrip("#")[i:i + 2], 16)) for i in (0, 2, 4))

    ice_focus = s["ice"]["400"]
    shared = {
        "DecorationFocus": ice_focus,
        "DecorationHover": ice_focus,
        "ForegroundActive": s["ice"]["300"],
        "ForegroundInactive": s["ink"]["4"],
        "ForegroundLink": s["ice"]["300"],
        "ForegroundVisited": s["ash"]["300"],
        "ForegroundNegative": a["critical"]["fg"],
        "ForegroundNeutral": a["caution"]["fg"],
        "ForegroundPositive": a["good"]["fg"],
    }

    # background normal, background alternate, foreground normal
    roles = {
        "Window": (s["void"]["10"], s["void"]["20"], s["ink"]["1"]),
        "View": (s["void"]["00"], s["void"]["10"], s["ink"]["1"]),
        "Button": (s["void"]["20"], s["void"]["30"], s["ink"]["1"]),
        "Selection": (s["ice"]["600"], s["ice"]["700"], s["ink"]["0"]),
        "Tooltip": (s["void"]["30"], s["void"]["40"], s["ink"]["1"]),
        "Complementary": (s["void"]["10"], s["void"]["20"], s["ink"]["1"]),
        "Header": (s["void"]["20"], s["void"]["30"], s["ink"]["1"]),
    }

    out = header("#")
    for role, (bg, alt, fg) in roles.items():
        out += f"[Colors:{role}]\n"
        out += f"BackgroundNormal={rgb(bg)}\n"
        out += f"BackgroundAlternate={rgb(alt)}\n"
        out += f"ForegroundNormal={rgb(fg)}\n"
        for key, hexval in shared.items():
            # Selection inverts: its foreground roles read against Ice, not void.
            if role == "Selection" and key == "ForegroundInactive":
                hexval = s["ink"]["2"]
            out += f"{key}={rgb(hexval)}\n"
        out += "\n"

    # Title bars. activeBlend/inactiveBlend are the gradient partner Breeze uses;
    # keeping them equal to the background is what removes the gradient.
    out += "[WM]\n"
    out += f"activeBackground={rgb(s['void']['20'])}\n"
    out += f"activeBlend={rgb(s['void']['20'])}\n"
    out += f"activeForeground={rgb(s['ink']['0'])}\n"
    out += f"inactiveBackground={rgb(s['void']['10'])}\n"
    out += f"inactiveBlend={rgb(s['void']['10'])}\n"
    out += f"inactiveForeground={rgb(s['ink']['3'])}\n"
    # The title bar font lives in [WM], and this whole section is replaced on
    # merge, so it has to be emitted here or it is dropped on the next run.
    out += f"activeFont={kde_font(p)}\n\n"

    # Disabled and inactive text. These control fading only, never hue; the
    # values are Breeze's, which are tuned and not worth reinventing.
    out += (
        "[ColorEffects:Disabled]\n"
        "Color=56,56,56\nColorAmount=0\nColorEffect=0\n"
        "ContrastAmount=0.65\nContrastEffect=1\n"
        "IntensityAmount=0.1\nIntensityEffect=2\n\n"
        "[ColorEffects:Inactive]\n"
        "ChangeSelectionColor=true\nColor=112,111,110\nColorAmount=0.025\n"
        "ColorEffect=2\nContrastAmount=0.1\nContrastEffect=2\n"
        "IntensityAmount=0\nIntensityEffect=0\n\n"
        "[General]\n"
        "ColorScheme=Voidashi\n"
        "Name=Voidashi\n"
        "shadeSortColumn=true\n"
    )
    return out


def merge_ini_keys(lines: list, keyed: dict) -> list:
    """Set specific keys in an INI file, leaving every other line untouched.

    For files where the keys we own sit beside keys another program writes, so
    replacing whole sections would throw away settings that are not ours. A key
    the file does not already carry is inserted under its section, and a section
    that does not exist is appended, because a fresh config must still come out
    complete rather than silently missing a font.
    """
    out, current = [], None
    seen = {section: set() for section in keyed}
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            current = stripped[1:-1]
        elif current in keyed and "=" in stripped:
            key = stripped.split("=", 1)[0].strip()
            if key in keyed[current]:
                seen[current].add(key)
                line = f"{key}={keyed[current][key]}"
        out.append(line)

    for section, pairs in keyed.items():
        missing = [k for k in pairs if k not in seen[section]]
        if not missing:
            continue
        # Locate the header the same way the loop above recognised it, on the
        # stripped line. Matching the raw line instead meant a header written
        # as "[General] " was found when replacing a key and not found here,
        # so a second [General] was appended to a file that already had one.
        at = next((i for i, l in enumerate(out) if l.strip() == f"[{section}]"), None)
        if at is None:
            out += ["", f"[{section}]"] + [f"{k}={pairs[k]}" for k in missing]
        else:
            for key in reversed(missing):
                out.insert(at + 1, f"{key}={pairs[key]}")
    return out


def kcm_input_merged(current: str, p: dict) -> str:
    """The cursor theme and size, which live in kcminputrc rather than kdeglobals.

    KDE's gtkconfig daemon reads them from here and writes them into both GTK
    settings.ini files, so this is the only place the cursor has to be set for
    Qt and GTK to agree.
    """
    t = p["typography"]
    keyed = {"Mouse": {"cursorTheme": t["cursor_theme"],
                       "cursorSize": str(t["cursor_size"])}}
    return "\n".join(merge_ini_keys(current.splitlines(), keyed)).strip() + "\n"


def kde_globals_merged(current: str, scheme: str, p: dict) -> str:
    """Replace the colour sections of kdeglobals and set the font keys.

    KDE applications read their palette from kdeglobals itself, not from the
    .colors file, which systemsettings only uses as a source to copy from. But
    kdeglobals also holds settings that are none of our business (animation
    factors, recent documents, shortcuts), and KDE tools write to it too. So
    this replaces the sections we own and copies everything else through
    untouched.

    Fonts are the exception to that shape, because they sit in [General]
    alongside keys we must not touch, so they are set key by key instead of by
    replacing the section. They matter beyond Qt: KDE's gtkconfig daemon reads
    them here and writes them into both GTK settings.ini files, which is why
    those two files stopped being worth hand-editing. See docs/MAINTENANCE.md.
    """
    owned = lambda name: (
        name.startswith("Colors:") or name == "WM" or name.startswith("ColorEffects:")
    )
    # section -> key -> value, merged in rather than replacing the section.
    t = p["typography"]
    keyed = {
        "General": {
            "font": kde_font(p),
            "fixed": kde_font(p, mono=True),
            "menuFont": kde_font(p),
            "toolBarFont": kde_font(p),
            "smallestReadableFont": kde_font(p, size_key="small_size"),
        },
        "Icons": {"Theme": t["icon_theme"]},
    }

    kept, section, keep_current = [], None, True
    for line in current.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped[1:-1]
            keep_current = not owned(section)
        if keep_current:
            kept.append(line)
    kept = merge_ini_keys(kept, keyed)

    # Drop the scheme's own [General], which would collide with the one already
    # in kdeglobals; only its colour sections are wanted here.
    body, section, emit = [], None, False
    for line in scheme.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped[1:-1]
            emit = owned(section)
        if emit:
            body.append(line)

    # strip() at both ends, not rstrip(): on a machine with no kdeglobals yet,
    # merge_ini_keys starts the section it appends with a blank line, so the
    # file came out beginning with one. The condition that used to stand here,
    # "if l.strip() or kept", was true for every line whenever kept was
    # non-empty and so never dropped anything.
    text = "\n".join(kept).strip() + "\n\n"
    text += "\n".join(body).rstrip() + "\n"
    return text


# =====================================================================
#  Orchestration
# =====================================================================

def generated_files(p: dict) -> dict:
    """Every file written wholesale, as path -> content.

    Kept as one mapping rather than a sequence of write() calls so that
    check_palette.py can compare what the palette says against what is on disk
    without duplicating the list, which would drift the first time one of them
    gained an entry.

    The three files merged into rather than written whole are in merged_files()
    below, because what they should contain depends on what is already in them.
    """
    r = roles.build(p)
    return {
        CONFIG / "kitty" / "voidashi-colors.conf": gen_kitty(p, r),
        CONFIG / "foot" / "voidashi-colors.ini": gen_foot(p, r),
        CONFIG / "ghostty" / "voidashi-colors": gen_ghostty(p, r),
        CONFIG / "alacritty" / "conf.d" / "voidashi-colors.toml": gen_alacritty(p, r),
        CONFIG / "hypr" / "conf" / "palette.lua": gen_hypr_palette(p),
        CONFIG / "theme" / "voidashi-colors.css": gen_gtk_css(p, r),
        CONFIG / "gtk-3.0" / "voidashi.css": gen_gtk_app_css(p, r, "gtk3"),
        CONFIG / "gtk-4.0" / "voidashi.css": gen_gtk_app_css(p, r, "gtk4"),
        CONFIG / "nvim" / "lua" / "voidashi" / "theme" / "palette.lua": gen_nvim_palette(p),
        REPO_ROOT / ".local" / "share" / "color-schemes" / "Voidashi.colors": gen_kde_colors(p),
    }


def merged_files(p: dict) -> dict:
    """The three written by merging, as path -> what to do with what is there.

    Each value takes the file's current text and returns what the generator
    would leave in it, so everything outside the sections it owns is copied
    through. That is why these cannot be a mapping of finished content the way
    generated_files() is.

    Kept here, and shaped this way, so check_palette.py can ask whether merging
    again would change the file. That question is the only thing that makes a
    hand-edit to an owned section visible: check_sync used to iterate
    generated_files() alone, so edits to all three went unreported.
    """
    r = roles.build(p)
    return {
        CONFIG / "wofi" / "style.css":
            lambda current: inlined_block(current, gen_gtk_css(p, r), "wofi/style.css"),
        CONFIG / "kdeglobals":
            lambda current: kde_globals_merged(current, gen_kde_colors(p), p),
        CONFIG / "kcminputrc":
            lambda current: kcm_input_merged(current, p),
    }


def main() -> None:
    p = load_palette()
    print("Generating Voidashi theme files from palette.json:")
    for path, content in generated_files(p).items():
        write(path, content)
    for path, merge in merged_files(p).items():
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        write(path, merge(current))
    print("Done. Diff the results before committing.")


if __name__ == "__main__":
    main()
