#!/usr/bin/env python3
"""Voidashi theme generator.

Reads palette.json (the single source of truth, transcribed from
docs/design/RICE-GUIDE.md and docs/design/DESIGN-SYSTEM.md) and writes the
color-only config partials each app natively includes. See RICE-GUIDE.md,
"Working rules for Claude Code".

Never hand-edit the files this script writes — they carry a GENERATED
header. Edit palette.json and rerun this script instead.
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
CONFIG = REPO_ROOT / ".config"

SOURCE_NOTE = "docs/design/RICE-GUIDE.md"


def load_palette() -> dict:
    with open(SCRIPT_DIR / "palette.json", encoding="utf-8") as f:
        return json.load(f)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(REPO_ROOT)}")


BLOCK_START = "/* >>> VOIDASHI COLORS (GENERATED) >>> */"
BLOCK_END = "/* <<< END VOIDASHI COLORS <<< */"


def inline_block(path: Path, content: str) -> None:
    """Replace the marked block inside a hand-written CSS file.

    For apps that cannot @import the shared partial. wofi hands its stylesheet
    to GTK as a string, so relative @import urls resolve against the process's
    cwd (usually $HOME) instead of the file's directory -- the colors silently
    never load. Inlining sidesteps path resolution entirely. Everything outside
    the markers stays hand-written.
    """
    original = path.read_text(encoding="utf-8")
    start = original.find(BLOCK_START)
    end = original.find(BLOCK_END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"{path.relative_to(REPO_ROOT)}: missing the "
            f"{BLOCK_START} / {BLOCK_END} markers the generator writes between."
        )
    block = f"{BLOCK_START}\n{content}{BLOCK_END}"
    path.write_text(original[:start] + block + original[end + len(BLOCK_END):], encoding="utf-8")
    print(f"  inlined into {path.relative_to(REPO_ROOT)}")


def header(comment_start: str, comment_end: str = "") -> str:
    lines = [
        "GENERATED by scripts/theme/generate_theme.py from scripts/theme/palette.json",
        "Do not hand-edit -- edit palette.json and rerun the generator.",
        f"Voidashi color scheme -- see {SOURCE_NOTE}",
    ]
    return "\n".join(f"{comment_start} {line}{comment_end}" for line in lines) + "\n\n"


def gen_kitty(p: dict) -> str:
    t, a = p["terminal"], p["ansi16"]
    out = header("#")
    out += f"background            {t['background']}\n"
    out += f"foreground            {t['foreground']}\n"
    out += f"cursor                {t['cursor']}\n"
    out += f"cursor_text_color     {t['cursor_text']}\n"
    out += f"selection_background  {t['selection_background']}\n"
    out += f"selection_foreground  {t['selection_foreground']}\n\n"
    for i, hexval in enumerate(a):
        out += f"color{i:<2} {hexval}\n"
    return out


def gen_foot(p: dict) -> str:
    t, a = p["terminal"], p["ansi16"]
    strip = lambda h: h.lstrip("#")
    out = header("#")
    out += "[colors-dark]\n"
    out += f"background={strip(t['background'])}\n"
    out += f"foreground={strip(t['foreground'])}\n"
    out += f"selection-foreground={strip(t['selection_foreground'])}\n"
    out += f"selection-background={strip(t['selection_background'])}\n"
    # [cursor].color was removed by foot; the replacement lives here as
    # "cursor = <text> <bg>" (see CLAUDE.md's foot/flexoki.ini note).
    out += f"cursor={strip(t['cursor_text'])} {strip(t['cursor'])}\n\n"
    for i in range(8):
        out += f"regular{i}={strip(a[i])}\n"
    out += "\n"
    for i in range(8):
        out += f"bright{i}={strip(a[8 + i])}\n"
    return out


def gen_ghostty(p: dict) -> str:
    t, a = p["terminal"], p["ansi16"]
    strip = lambda h: h.lstrip("#")
    out = header("#")
    out += f"background = {strip(t['background'])}\n"
    out += f"foreground = {strip(t['foreground'])}\n"
    out += f"cursor-color = {strip(t['cursor'])}\n"
    out += f"cursor-text = {strip(t['cursor_text'])}\n"
    out += f"selection-background = {strip(t['selection_background'])}\n"
    out += f"selection-foreground = {strip(t['selection_foreground'])}\n\n"
    for i, hexval in enumerate(a):
        out += f"palette = {i}={hexval}\n"
    return out


def gen_alacritty(p: dict) -> str:
    t, a = p["terminal"], p["ansi16"]
    out = header("#")
    out += f"[colors.primary]\nbackground = '{t['background']}'\nforeground = '{t['foreground']}'\n\n"
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    out += "[colors.normal]\n"
    for i, name in enumerate(names):
        out += f"{name} = '{a[i]}'\n"
    out += "\n[colors.bright]\n"
    for i, name in enumerate(names):
        out += f"{name} = '{a[8 + i]}'\n"
    out += f"\n[colors.cursor]\ntext = '{t['cursor_text']}'\ncursor = '{t['cursor']}'\n"
    out += f"\n[colors.selection]\nbackground = '{t['selection_background']}'\ntext = '{t['selection_foreground']}'\n"
    return out


def gen_hypr_palette(p: dict) -> str:
    # Lua table keys that look like numbers ("00", "400") need bracket-string
    # form; only alpha keys like "deep" can be written bare.
    lua_key = lambda shade: shade if shade.isidentifier() else f'["{shade}"]'
    out = header("--")
    out += "return {\n"
    for scale_name, shades in p["scales"].items():
        out += f"    {scale_name} = {{\n"
        for shade, hexval in shades.items():
            out += f'        {lua_key(shade)} = "{hexval}",\n'
        out += "    },\n"
    out += "    alert = {\n"
    for name, entry in p["alert"].items():
        out += f'        {name} = {{ fg = "{entry["fg"]}", bg = "{entry["bg"]}", border = "{entry["border"]}" }},\n'
    out += "    },\n"
    g = p["geometry"]
    out += "    geometry = {\n"
    out += f'        radius_floating = {g["radius_floating"]},\n'
    out += f'        radius_docked = {g["radius_docked"]},\n'
    out += "    },\n"
    out += "}\n"
    return out


def gen_gtk_css(p: dict) -> str:
    out = header("/*", " */")
    for scale_name, shades in p["scales"].items():
        for shade, hexval in shades.items():
            out += f"@define-color {scale_name}-{shade} {hexval};\n"
        out += "\n"
    for name, entry in p["alert"].items():
        out += f"@define-color alert-{name} {entry['fg']};\n"
        out += f"@define-color alert-{name}-bg {entry['bg']};\n"
        out += f"@define-color alert-{name}-border {entry['border']};\n"
    out += "\n"
    out += f"@define-color focus-ring {p['focus_ring']};\n"
    g = p["geometry"]
    out += (
        "\n/* Non-colour tokens, for reference. GTK3 -- waybar, wofi, wlogout -- has no\n"
        "   CSS custom properties, so these cannot be consumed as variables there the\n"
        "   way the colours above are: each GTK3 stylesheet carries the literal and\n"
        "   points back at palette.json. swaync is GTK4 and does read them.\n"
        f"     radius, floating surface: {g['radius_floating']}px\n"
        f"     radius, docked surface:   {g['radius_docked']}px\n"
        f"     UI font weight:           {g['font_weight_ui']} */\n"
    )
    return out


def gen_gtk_app_css(p: dict, toolkit: str) -> str:
    """Named-colour overrides for ordinary GTK applications.

    Distinct from gen_gtk_css, which exports the raw palette for stylesheets we
    write ourselves. This one maps the palette onto the names GTK and libadwaita
    already paint from, so applications nobody wrote a stylesheet for follow the
    desktop: pavucontrol, zenity, file choosers, network dialogs.

    Surfaces follow RICE-GUIDE.md's hierarchy. The window chrome sits at void-10
    and content at void-00, so a text view reads as recessed into the window
    rather than floating on it, matching how the terminals are built.
    """
    s, a, g = p["scales"], p["alert"], p["geometry"]
    out = header("/*", " */")
    out += f"/* {toolkit} named colours, mapped from palette.json */\n\n"

    if toolkit == "gtk4":
        pairs = [
            ("window_bg_color", s["void"]["10"]),
            ("window_fg_color", s["ink"]["1"]),
            ("view_bg_color", s["void"]["00"]),
            ("view_fg_color", s["ink"]["1"]),
            ("headerbar_bg_color", s["void"]["20"]),
            ("headerbar_fg_color", s["ink"]["1"]),
            ("headerbar_border_color", s["edge"]["20"]),
            ("headerbar_backdrop_color", s["void"]["10"]),
            ("headerbar_shade_color", s["edge"]["10"]),
            ("sidebar_bg_color", s["void"]["10"]),
            ("sidebar_fg_color", s["ink"]["2"]),
            ("sidebar_border_color", s["edge"]["20"]),
            ("sidebar_backdrop_color", s["void"]["10"]),
            ("secondary_sidebar_bg_color", s["void"]["10"]),
            ("secondary_sidebar_fg_color", s["ink"]["2"]),
            ("card_bg_color", s["void"]["20"]),
            ("card_fg_color", s["ink"]["1"]),
            ("dialog_bg_color", s["void"]["20"]),
            ("dialog_fg_color", s["ink"]["1"]),
            ("popover_bg_color", s["void"]["20"]),
            ("popover_fg_color", s["ink"]["1"]),
            ("thumbnail_bg_color", s["void"]["20"]),
            ("thumbnail_fg_color", s["ink"]["1"]),
            ("shade_color", s["void"]["00"]),
            ("scrollbar_outline_color", s["edge"]["20"]),
            # Focus and selection are Ice everywhere in this desktop.
            ("accent_bg_color", s["ice"]["600"]),
            ("accent_fg_color", s["ink"]["0"]),
            ("accent_color", s["ice"]["300"]),
            ("destructive_bg_color", a["critical"]["bg"]),
            ("destructive_fg_color", a["critical"]["fg"]),
            ("destructive_color", a["critical"]["fg"]),
            ("success_bg_color", a["good"]["bg"]),
            ("success_fg_color", a["good"]["fg"]),
            ("success_color", a["good"]["fg"]),
            ("warning_bg_color", a["caution"]["bg"]),
            ("warning_fg_color", a["caution"]["fg"]),
            ("warning_color", a["caution"]["fg"]),
            ("error_bg_color", a["critical"]["bg"]),
            ("error_fg_color", a["critical"]["fg"]),
            ("error_color", a["critical"]["fg"]),
            ("borders", s["edge"]["20"]),
        ]
    else:
        pairs = [
            ("theme_bg_color", s["void"]["10"]),
            ("theme_fg_color", s["ink"]["1"]),
            ("theme_base_color", s["void"]["00"]),
            ("theme_text_color", s["ink"]["1"]),
            ("theme_selected_bg_color", s["ice"]["600"]),
            ("theme_selected_fg_color", s["ink"]["0"]),
            ("theme_unfocused_bg_color", s["void"]["10"]),
            ("theme_unfocused_fg_color", s["ink"]["2"]),
            ("theme_unfocused_base_color", s["void"]["00"]),
            ("theme_unfocused_text_color", s["ink"]["2"]),
            ("theme_unfocused_selected_bg_color", s["ice"]["700"]),
            ("theme_unfocused_selected_fg_color", s["ink"]["1"]),
            ("insensitive_bg_color", s["void"]["20"]),
            ("insensitive_fg_color", s["ink"]["4"]),
            ("insensitive_base_color", s["void"]["10"]),
            ("borders", s["edge"]["20"]),
            ("unfocused_borders", s["edge"]["10"]),
            ("warning_color", a["caution"]["fg"]),
            ("error_color", a["critical"]["fg"]),
            ("success_color", a["good"]["fg"]),
            ("link_color", s["ice"]["300"]),
            ("visited_link_color", s["ash"]["300"]),
        ]

    for name, hexval in pairs:
        out += f"@define-color {name} {hexval};\n"

    if toolkit == "gtk4":
        # GTK 4.16 moved this stylesheet onto CSS custom properties, and on
        # 4.22 the accent responds only to those: with @define-color
        # accent_bg_color set to one colour and --accent-bg-color to another in
        # the same file, the custom property is what renders. Surfaces still
        # honour @define-color, so both forms are emitted rather than guessing
        # which of the two any given GTK version reads.
        out += "\n:root {\n"
        for name, hexval in pairs:
            out += f"    --{name.replace('_', '-')}: {hexval};\n"
        out += "}\n"

    # Popovers, dialogs and menus float over other content, so they take the
    # floating radius; see RICE-GUIDE.md, "Form".
    r = g["radius_floating"]
    out += f"""
popover,
popover > contents,
menu,
.menu,
.context-menu,
tooltip,
tooltip.background,
messagedialog,
dialog {{
    border-radius: {r}px;
}}

/* Widgets that sit inside a surface stay square, matching the shell. */
button,
entry,
textview,
scrollbar,
notebook,
headerbar,
checkbutton check,
radiobutton radio {{
    border-radius: 0;
}}
"""
    return out


def gen_nvim_palette(p: dict) -> str:
    """Raw palette for the Neovim colorscheme, same shape as the Hyprland one.

    Only colours belong here. The semantic layer that turns them into roles
    lives beside it in roles.lua, hand-written, and the highlight groups read
    from that rather than from this file. Keeping the two apart is what lets the
    theme be recoloured without touching three hundred group definitions.
    """
    lua_key = lambda shade: shade if shade.isidentifier() else f'["{shade}"]'
    out = header("--")
    out += "return {\n"
    for scale_name, shades in p["scales"].items():
        out += f"    {scale_name} = {{\n"
        for shade, hexval in shades.items():
            out += f'        {lua_key(shade)} = "{hexval}",\n'
        out += "    },\n"
    out += "    alert = {\n"
    for name, entry in p["alert"].items():
        out += f'        {name} = {{ fg = "{entry["fg"]}", bg = "{entry["bg"]}", border = "{entry["border"]}" }},\n'
    out += "    },\n"
    # The ANSI table verbatim, so :terminal matches every other terminal and TUI
    # on the machine. That equivalence is a non-negotiable in RICE-GUIDE.md.
    out += "    ansi = {\n"
    for i, hexval in enumerate(p["ansi16"]):
        out += f'        [{i}] = "{hexval}",\n'
    out += "    },\n"
    out += "}\n"
    return out


def merge_kde_globals(path: Path, scheme: str) -> None:
    """Replace only the colour sections of kdeglobals, leaving the rest alone.

    KDE applications read their palette from kdeglobals itself, not from the
    .colors file, which systemsettings only uses as a source to copy from. But
    kdeglobals also holds settings that are none of our business (animation
    factors, recent documents, shortcuts), and KDE tools write to it too. So
    this replaces the sections we own and copies everything else through
    untouched.
    """
    owned = lambda name: (
        name.startswith("Colors:") or name == "WM" or name.startswith("ColorEffects:")
    )

    kept, current, keep_current = [], None, True
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("[") and stripped.endswith("]"):
                current = stripped[1:-1]
                keep_current = not owned(current)
            if keep_current:
                kept.append(line)

    # Drop the scheme's own [General], which would collide with the one already
    # in kdeglobals; only its colour sections are wanted here.
    body, current, emit = [], None, False
    for line in scheme.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            current = stripped[1:-1]
            emit = owned(current)
        if emit:
            body.append(line)

    text = "\n".join(l for l in kept if l.strip() or kept).rstrip() + "\n\n"
    text += "\n".join(body).rstrip() + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"  merged colours into {path.relative_to(REPO_ROOT)}")


def gen_kde_colors(p: dict) -> str:
    """KDE colour scheme, for the Qt half of the desktop.

    Nine KDE applications are installed (dolphin, ark, gwenview, kate,
    spectacle, and so on) and they read their colours from kdeglobals rather
    than from anything GTK. The format is INI with one block per role and
    values as "R,G,B" rather than hex.

    The blocks are not interchangeable: Window is the chrome, View is the
    content area a list or a text buffer draws on, Button is a raised control,
    Tooltip floats above everything. Mapping them all to one colour is what
    makes a Qt application look flat and wrong.
    """
    s, a = p["scales"], p["alert"]
    rgb = lambda h: ",".join(str(int(h.lstrip("#")[i:i + 2], 16)) for i in (0, 2, 4))

    ice_focus = s["ice"]["400"]
    shared = {
        "DecorationFocus": ice_focus,
        "DecorationHover": ice_focus,
        "ForegroundActive": s["ice"]["300"],
        "ForegroundInactive": s["ink"]["4"],
        "ForegroundLink": s["ice"]["300"],
        "ForegroundVisited": s["ash"]["300"],
        "ForegroundNegative": a["critical"]["fg"],
        "ForegroundNeutral": a["caution"]["fg"],
        "ForegroundPositive": a["good"]["fg"],
    }

    # background normal, background alternate, foreground normal
    roles = {
        "Window": (s["void"]["10"], s["void"]["20"], s["ink"]["1"]),
        "View": (s["void"]["00"], s["void"]["10"], s["ink"]["1"]),
        "Button": (s["void"]["20"], s["void"]["30"], s["ink"]["1"]),
        "Selection": (s["ice"]["600"], s["ice"]["700"], s["ink"]["0"]),
        "Tooltip": (s["void"]["30"], s["void"]["40"], s["ink"]["1"]),
        "Complementary": (s["void"]["10"], s["void"]["20"], s["ink"]["1"]),
        "Header": (s["void"]["20"], s["void"]["30"], s["ink"]["1"]),
    }

    out = header("#")
    for role, (bg, alt, fg) in roles.items():
        out += f"[Colors:{role}]\n"
        out += f"BackgroundNormal={rgb(bg)}\n"
        out += f"BackgroundAlternate={rgb(alt)}\n"
        out += f"ForegroundNormal={rgb(fg)}\n"
        for key, hexval in shared.items():
            # Selection inverts: its foreground roles read against Ice, not void.
            if role == "Selection" and key == "ForegroundInactive":
                hexval = s["ink"]["2"]
            out += f"{key}={rgb(hexval)}\n"
        out += "\n"

    # Title bars. activeBlend/inactiveBlend are the gradient partner Breeze uses;
    # keeping them equal to the background is what removes the gradient.
    out += "[WM]\n"
    out += f"activeBackground={rgb(s['void']['20'])}\n"
    out += f"activeBlend={rgb(s['void']['20'])}\n"
    out += f"activeForeground={rgb(s['ink']['0'])}\n"
    out += f"inactiveBackground={rgb(s['void']['10'])}\n"
    out += f"inactiveBlend={rgb(s['void']['10'])}\n"
    out += f"inactiveForeground={rgb(s['ink']['3'])}\n\n"

    # Disabled and inactive text. These control fading only, never hue; the
    # values are Breeze's, which are tuned and not worth reinventing.
    out += (
        "[ColorEffects:Disabled]\n"
        "Color=56,56,56\nColorAmount=0\nColorEffect=0\n"
        "ContrastAmount=0.65\nContrastEffect=1\n"
        "IntensityAmount=0.1\nIntensityEffect=2\n\n"
        "[ColorEffects:Inactive]\n"
        "ChangeSelectionColor=true\nColor=112,111,110\nColorAmount=0.025\n"
        "ColorEffect=2\nContrastAmount=0.1\nContrastEffect=2\n"
        "IntensityAmount=0\nIntensityEffect=0\n\n"
        "[General]\n"
        "ColorScheme=Voidashi\n"
        "Name=Voidashi\n"
        "shadeSortColumn=true\n"
    )
    return out


def main() -> None:
    p = load_palette()
    print("Generating Voidashi theme files from palette.json:")
    write(CONFIG / "kitty" / "voidashi-colors.conf", gen_kitty(p))
    write(CONFIG / "foot" / "voidashi-colors.ini", gen_foot(p))
    write(CONFIG / "ghostty" / "voidashi-colors", gen_ghostty(p))
    write(CONFIG / "alacritty" / "conf.d" / "voidashi-colors.toml", gen_alacritty(p))
    write(CONFIG / "hypr" / "conf" / "palette.lua", gen_hypr_palette(p))
    gtk_css = gen_gtk_css(p)
    write(CONFIG / "theme" / "voidashi-colors.css", gtk_css)
    inline_block(CONFIG / "wofi" / "style.css", gtk_css)
    write(CONFIG / "gtk-3.0" / "voidashi.css", gen_gtk_app_css(p, "gtk3"))
    write(CONFIG / "gtk-4.0" / "voidashi.css", gen_gtk_app_css(p, "gtk4"))
    write(CONFIG / "nvim" / "lua" / "voidashi" / "theme" / "palette.lua", gen_nvim_palette(p))
    kde = gen_kde_colors(p)
    write(REPO_ROOT / ".local" / "share" / "color-schemes" / "Voidashi.colors", kde)
    merge_kde_globals(CONFIG / "kdeglobals", kde)
    print("Done. Diff the results before committing.")


if __name__ == "__main__":
    main()
