#!/usr/bin/env python3
"""Voidashi theme generator.

Reads palette.json (the single source of truth, transcribed from
docs/design/RICE-GUIDE.md and docs/design/DESIGN-SYSTEM.md) and writes the
color-only config partials each app natively includes. See RICE-GUIDE.md,
"Working rules for Claude Code".

Never hand-edit the files this script writes — they carry a GENERATED
header. Edit palette.json and rerun this script instead.
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
CONFIG = REPO_ROOT / ".config"

SOURCE_NOTE = "docs/design/RICE-GUIDE.md"


def load_palette() -> dict:
    with open(SCRIPT_DIR / "palette.json", encoding="utf-8") as f:
        return json.load(f)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"  wrote {path.relative_to(REPO_ROOT)}")


def header(comment_start: str, comment_end: str = "") -> str:
    lines = [
        "GENERATED by scripts/theme/generate_theme.py from scripts/theme/palette.json",
        "Do not hand-edit -- edit palette.json and rerun the generator.",
        f"Voidashi color scheme -- see {SOURCE_NOTE}",
    ]
    return "\n".join(f"{comment_start} {line}{comment_end}" for line in lines) + "\n\n"


def gen_kitty(p: dict) -> str:
    t, a = p["terminal"], p["ansi16"]
    out = header("#")
    out += f"background            {t['background']}\n"
    out += f"foreground            {t['foreground']}\n"
    out += f"cursor                {t['cursor']}\n"
    out += f"cursor_text_color     {t['cursor_text']}\n"
    out += f"selection_background  {t['selection_background']}\n"
    out += f"selection_foreground  {t['selection_foreground']}\n\n"
    for i, hexval in enumerate(a):
        out += f"color{i:<2} {hexval}\n"
    return out


def gen_foot(p: dict) -> str:
    t, a = p["terminal"], p["ansi16"]
    strip = lambda h: h.lstrip("#")
    out = header("#")
    out += "[colors-dark]\n"
    out += f"background={strip(t['background'])}\n"
    out += f"foreground={strip(t['foreground'])}\n"
    out += f"selection-foreground={strip(t['selection_foreground'])}\n"
    out += f"selection-background={strip(t['selection_background'])}\n"
    # [cursor].color was removed by foot; the replacement lives here as
    # "cursor = <text> <bg>" (see CLAUDE.md's foot/flexoki.ini note).
    out += f"cursor={strip(t['cursor_text'])} {strip(t['cursor'])}\n\n"
    for i in range(8):
        out += f"regular{i}={strip(a[i])}\n"
    out += "\n"
    for i in range(8):
        out += f"bright{i}={strip(a[8 + i])}\n"
    return out


def gen_ghostty(p: dict) -> str:
    t, a = p["terminal"], p["ansi16"]
    strip = lambda h: h.lstrip("#")
    out = header("#")
    out += f"background = {strip(t['background'])}\n"
    out += f"foreground = {strip(t['foreground'])}\n"
    out += f"cursor-color = {strip(t['cursor'])}\n"
    out += f"cursor-text = {strip(t['cursor_text'])}\n"
    out += f"selection-background = {strip(t['selection_background'])}\n"
    out += f"selection-foreground = {strip(t['selection_foreground'])}\n\n"
    for i, hexval in enumerate(a):
        out += f"palette = {i}={hexval}\n"
    return out


def gen_alacritty(p: dict) -> str:
    t, a = p["terminal"], p["ansi16"]
    out = header("#")
    out += f"[colors.primary]\nbackground = '{t['background']}'\nforeground = '{t['foreground']}'\n\n"
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    out += "[colors.normal]\n"
    for i, name in enumerate(names):
        out += f"{name} = '{a[i]}'\n"
    out += "\n[colors.bright]\n"
    for i, name in enumerate(names):
        out += f"{name} = '{a[8 + i]}'\n"
    out += f"\n[colors.cursor]\ntext = '{t['cursor_text']}'\ncursor = '{t['cursor']}'\n"
    out += f"\n[colors.selection]\nbackground = '{t['selection_background']}'\ntext = '{t['selection_foreground']}'\n"
    return out


def gen_hypr_palette(p: dict) -> str:
    # Lua table keys that look like numbers ("00", "400") need bracket-string
    # form; only alpha keys like "deep" can be written bare.
    lua_key = lambda shade: shade if shade.isidentifier() else f'["{shade}"]'
    out = header("--")
    out += "return {\n"
    for scale_name, shades in p["scales"].items():
        out += f"    {scale_name} = {{\n"
        for shade, hexval in shades.items():
            out += f'        {lua_key(shade)} = "{hexval}",\n'
        out += "    },\n"
    out += "    alert = {\n"
    for name, entry in p["alert"].items():
        out += f'        {name} = {{ fg = "{entry["fg"]}", bg = "{entry["bg"]}", border = "{entry["border"]}" }},\n'
    out += "    },\n"
    out += "}\n"
    return out


def gen_gtk_css(p: dict) -> str:
    out = header("/*", " */")
    for scale_name, shades in p["scales"].items():
        for shade, hexval in shades.items():
            out += f"@define-color {scale_name}-{shade} {hexval};\n"
        out += "\n"
    for name, entry in p["alert"].items():
        out += f"@define-color alert-{name} {entry['fg']};\n"
        out += f"@define-color alert-{name}-bg {entry['bg']};\n"
        out += f"@define-color alert-{name}-border {entry['border']};\n"
    out += "\n"
    out += f"@define-color focus-ring {p['focus_ring']};\n"
    return out


def main() -> None:
    p = load_palette()
    print("Generating Voidashi theme files from palette.json:")
    write(CONFIG / "kitty" / "voidashi-colors.conf", gen_kitty(p))
    write(CONFIG / "foot" / "voidashi-colors.ini", gen_foot(p))
    write(CONFIG / "ghostty" / "voidashi-colors", gen_ghostty(p))
    write(CONFIG / "alacritty" / "conf.d" / "voidashi-colors.toml", gen_alacritty(p))
    write(CONFIG / "hypr" / "conf" / "palette.lua", gen_hypr_palette(p))
    write(CONFIG / "theme" / "voidashi-colors.css", gen_gtk_css(p))
    print("Done. Diff the results before committing.")


if __name__ == "__main__":
    main()
