# =====================================================================
# HYPRLAND CONFIG PRINCIPAL
# =====================================================================

# Inclui cada seção modularizada
source = ~/.config/hypr/conf.d.legacy/monitors.conf
source = ~/.config/hypr/conf.d.legacy/env_vars.conf
source = ~/.config/hypr/conf.d.legacy/programs.conf
source = ~/.config/hypr/conf.d.legacy/autostart.conf
source = ~/.config/hypr/conf.d.legacy/appearance.conf
source = ~/.config/hypr/conf.d.legacy/decoration.conf
source = ~/.config/hypr/conf.d.legacy/animations.conf
source = ~/.config/hypr/conf.d.legacy/layouts.conf
source = ~/.config/hypr/conf.d.legacy/misc.conf
source = ~/.config/hypr/conf.d.legacy/input.conf
source = ~/.config/hypr/conf.d.legacy/gestures.conf
source = ~/.config/hypr/conf.d.legacy/binds.conf
source = ~/.config/hypr/conf.d.legacy/window_rules.conf