-- =====================================================================
--  VOIDASHI -- grupos de highlight
-- =====================================================================
-- Lê apenas de roles.lua, nunca de palette.lua. Se uma cor crua aparecer
-- aqui, é bug: significa que um papel novo precisou existir e não foi criado.
--
-- Organizado nas mesmas camadas que o kanagawa separa, porque a divisão é boa:
-- editor, sintaxe legada, treesitter, LSP e diagnósticos, e por fim os plugins
-- que desenham interface própria.

local r = require("voidashi.theme.roles")
local ui, syn, diag, vcs, diff = r.ui, r.syn, r.diag, r.vcs, r.diff
local p = r.palette

local M = {}

function M.get(opts)
  opts = opts or {}
  -- Com transparência o editor mostra o fundo do terminal. Superfícies que
  -- flutuam acima dele continuam opacas: um popup translúcido sobre texto é
  -- ilegível, que é a mesma razão pela qual o guia manda popups opacos.
  local bg = opts.transparent and "NONE" or ui.bg

  return {
    -- ===== Editor ====================================================
    Normal       = { fg = ui.fg, bg = bg },
    NormalNC     = { link = "Normal" },
    NormalFloat  = { fg = ui.fg, bg = ui.bg_p1 },
    FloatBorder  = { fg = ui.border, bg = ui.bg_p1 },
    FloatTitle   = { fg = syn.fun, bg = ui.bg_p1, bold = true },
    FloatFooter  = { fg = ui.fg_dim, bg = ui.bg_p1 },

    Cursor       = { fg = ui.bg, bg = p.bordeaux["300"] },
    lCursor      = { link = "Cursor" },
    CursorIM     = { link = "Cursor" },
    TermCursor   = { link = "Cursor" },
    CursorLine   = { bg = ui.bg_cursorline },
    CursorColumn = { link = "CursorLine" },
    ColorColumn  = { bg = ui.bg_dim },
    CursorLineNr = { fg = p.bordeaux["300"], bold = true },
    LineNr       = { fg = ui.nontext },
    SignColumn   = { bg = bg },
    FoldColumn   = { fg = ui.nontext, bg = bg },
    Folded       = { fg = ui.fg_dim, bg = ui.bg_m1 },

    Visual       = { bg = ui.bg_visual },
    VisualNOS    = { link = "Visual" },
    Search       = { fg = ui.fg, bg = ui.bg_search },
    IncSearch    = { fg = ui.bg, bg = p.bronze["300"] },
    CurSearch    = { link = "IncSearch" },
    Substitute   = { fg = ui.bg, bg = diag.warning },
    MatchParen   = { fg = p.bordeaux["200"], bold = true },

    Pmenu        = { fg = ui.pmenu.fg, bg = ui.pmenu.bg },
    PmenuSel     = { fg = ui.pmenu.fg_sel, bg = ui.pmenu.bg_sel },
    PmenuKind    = { fg = syn.type, bg = ui.pmenu.bg },
    PmenuKindSel = { fg = syn.type, bg = ui.pmenu.bg_sel },
    PmenuExtra   = { fg = ui.fg_dim, bg = ui.pmenu.bg },
    PmenuExtraSel = { fg = ui.fg_dim, bg = ui.pmenu.bg_sel },
    PmenuSbar    = { bg = ui.pmenu.bg_sbar },
    PmenuThumb   = { bg = ui.pmenu.bg_thumb },
    WildMenu     = { link = "PmenuSel" },

    StatusLine   = { fg = ui.fg, bg = ui.bg_p1 },
    StatusLineNC = { fg = ui.fg_dim, bg = ui.bg_m1 },
    TabLine      = { fg = ui.fg_dim, bg = ui.bg_m1 },
    TabLineFill  = { bg = ui.bg_m1 },
    TabLineSel   = { fg = ui.fg, bg = ui.bg_p1 },
    WinBar       = { fg = ui.fg_dim, bg = bg },
    WinBarNC     = { fg = ui.nontext, bg = bg },
    WinSeparator = { fg = ui.border },
    VertSplit    = { link = "WinSeparator" },

    NonText      = { fg = ui.nontext },
    Whitespace   = { fg = ui.whitespace },
    SpecialKey   = { fg = ui.special },
    EndOfBuffer  = { fg = ui.nontext },
    Conceal      = { fg = ui.fg_dim },
    Directory    = { fg = syn.fun },
    Title        = { fg = syn.fun, bold = true },
    Question     = { fg = diag.info },
    MoreMsg      = { fg = diag.ok },
    ModeMsg      = { fg = ui.fg, bold = true },
    MsgArea      = { fg = ui.fg },
    MsgSeparator = { fg = ui.border },
    ErrorMsg     = { fg = diag.error },
    WarningMsg   = { fg = diag.warning },

    QuickFixLine = { bg = ui.bg_p1 },
    debugPC      = { bg = diff.delete },
    debugBreakpoint = { fg = diag.error },

    SpellBad     = { undercurl = true, sp = diag.error },
    SpellCap     = { undercurl = true, sp = diag.warning },
    SpellLocal   = { undercurl = true, sp = diag.info },
    SpellRare    = { undercurl = true, sp = diag.hint },

    DiffAdd      = { bg = diff.add },
    DiffDelete   = { fg = diag.error, bg = diff.delete },
    DiffChange   = { bg = diff.change },
    DiffText     = { bg = diff.text },
    Added        = { fg = vcs.added },
    Removed      = { fg = vcs.removed },
    Changed      = { fg = vcs.changed },

    -- ===== Sintaxe ===================================================
    Comment      = { fg = syn.comment, italic = true },
    Constant     = { fg = syn.constant },
    String       = { fg = syn.string },
    Character    = { fg = syn.string },
    Number       = { fg = syn.number },
    Float        = { link = "Number" },
    Boolean      = { fg = syn.constant, bold = true },
    Identifier   = { fg = syn.identifier },
    Function     = { fg = syn.fun },
    Statement    = { fg = syn.statement },
    Conditional  = { fg = syn.keyword },
    Repeat       = { fg = syn.keyword },
    Label        = { fg = syn.keyword },
    Operator     = { fg = syn.operator },
    Keyword      = { fg = syn.keyword, italic = true },
    Exception    = { fg = syn.keyword },
    PreProc      = { fg = syn.preproc },
    Include      = { fg = syn.preproc },
    Define       = { fg = syn.preproc },
    Macro        = { fg = syn.preproc },
    PreCondit    = { fg = syn.preproc },
    Type         = { fg = syn.type },
    StorageClass = { fg = syn.keyword },
    Structure    = { fg = syn.type },
    Typedef      = { fg = syn.type },
    Special      = { fg = syn.special1 },
    SpecialChar  = { fg = syn.special2 },
    Tag          = { fg = syn.special1 },
    Delimiter    = { fg = syn.punct },
    SpecialComment = { fg = syn.special1, italic = true },
    Debug        = { fg = syn.special2 },
    Underlined   = { fg = syn.fun, underline = true },
    Ignore       = { fg = ui.nontext },
    Error        = { fg = diag.error },
    Todo         = { fg = ui.bg, bg = diag.info, bold = true },

    -- ===== Treesitter ================================================
    ["@variable"]              = { fg = syn.variable },
    ["@variable.builtin"]      = { fg = syn.special2, italic = true },
    ["@variable.parameter"]    = { fg = syn.parameter },
    ["@variable.member"]       = { fg = syn.identifier },
    ["@constant"]              = { fg = syn.constant },
    ["@constant.builtin"]      = { fg = syn.special2 },
    ["@constant.macro"]        = { fg = syn.preproc },
    ["@module"]                = { fg = syn.type },
    ["@label"]                 = { fg = syn.keyword },
    ["@string"]                = { fg = syn.string },
    ["@string.documentation"]  = { fg = syn.comment },
    ["@string.regexp"]         = { fg = syn.regex },
    ["@string.escape"]         = { fg = syn.special2, bold = true },
    ["@string.special"]        = { fg = syn.special1 },
    ["@string.special.url"]    = { fg = syn.special1, underline = true },
    ["@character"]             = { fg = syn.string },
    ["@character.special"]     = { fg = syn.special2 },
    ["@boolean"]               = { fg = syn.constant, bold = true },
    ["@number"]                = { fg = syn.number },
    ["@number.float"]          = { fg = syn.number },
    ["@type"]                  = { fg = syn.type },
    ["@type.builtin"]          = { fg = syn.type, italic = true },
    ["@type.definition"]       = { fg = syn.type },
    ["@attribute"]             = { fg = syn.preproc },
    ["@property"]              = { fg = syn.identifier },
    ["@function"]              = { fg = syn.fun },
    ["@function.builtin"]      = { fg = syn.fun, italic = true },
    ["@function.call"]         = { fg = syn.fun },
    ["@function.macro"]        = { fg = syn.preproc },
    ["@function.method"]       = { fg = syn.fun },
    ["@function.method.call"]  = { fg = syn.fun },
    ["@constructor"]           = { fg = syn.type },
    ["@operator"]              = { fg = syn.operator },
    ["@keyword"]               = { fg = syn.keyword, italic = true },
    ["@keyword.function"]      = { fg = syn.keyword, italic = true },
    ["@keyword.operator"]      = { fg = syn.operator },
    ["@keyword.import"]        = { fg = syn.preproc },
    ["@keyword.return"]        = { fg = syn.keyword, italic = true },
    ["@keyword.exception"]     = { fg = syn.keyword },
    ["@keyword.conditional"]   = { fg = syn.keyword, italic = true },
    ["@keyword.repeat"]        = { fg = syn.keyword, italic = true },
    ["@keyword.directive"]     = { fg = syn.preproc },
    ["@punctuation.delimiter"] = { fg = syn.punct },
    ["@punctuation.bracket"]   = { fg = syn.punct },
    ["@punctuation.special"]   = { fg = syn.special2 },
    ["@comment"]               = { fg = syn.comment, italic = true },
    ["@comment.error"]         = { fg = ui.bg, bg = diag.error, bold = true },
    ["@comment.warning"]       = { fg = ui.bg, bg = diag.warning, bold = true },
    ["@comment.todo"]          = { fg = ui.bg, bg = diag.info, bold = true },
    ["@comment.note"]          = { fg = ui.bg, bg = diag.hint, bold = true },
    ["@markup.strong"]         = { bold = true },
    ["@markup.italic"]         = { italic = true },
    ["@markup.strikethrough"]  = { strikethrough = true },
    ["@markup.underline"]      = { underline = true },
    ["@markup.heading"]        = { fg = syn.fun, bold = true },
    ["@markup.quote"]          = { fg = syn.comment, italic = true },
    ["@markup.math"]           = { fg = syn.special1 },
    ["@markup.link"]           = { fg = syn.special1 },
    ["@markup.link.url"]       = { fg = syn.special1, underline = true },
    ["@markup.link.label"]     = { fg = syn.fun },
    ["@markup.raw"]            = { fg = syn.string },
    ["@markup.list"]           = { fg = syn.punct },
    ["@markup.list.checked"]   = { fg = diag.ok },
    ["@markup.list.unchecked"] = { fg = ui.fg_dim },
    ["@diff.plus"]             = { fg = vcs.added },
    ["@diff.minus"]            = { fg = vcs.removed },
    ["@diff.delta"]            = { fg = vcs.changed },
    ["@tag"]                   = { fg = syn.keyword },
    ["@tag.builtin"]           = { fg = syn.keyword },
    ["@tag.attribute"]         = { fg = syn.parameter },
    ["@tag.delimiter"]         = { fg = syn.punct },

    -- ===== LSP e diagnósticos ========================================
    -- A cor nunca carrega o estado sozinha: o sinal na gutter traz um glifo,
    -- e o sublinhado ondulado é uma segunda pista de forma.
    DiagnosticError            = { fg = diag.error },
    DiagnosticWarn             = { fg = diag.warning },
    DiagnosticInfo             = { fg = diag.info },
    DiagnosticHint             = { fg = diag.hint },
    DiagnosticOk               = { fg = diag.ok },
    DiagnosticSignError        = { fg = diag.error, bg = bg },
    DiagnosticSignWarn         = { fg = diag.warning, bg = bg },
    DiagnosticSignInfo         = { fg = diag.info, bg = bg },
    DiagnosticSignHint         = { fg = diag.hint, bg = bg },
    DiagnosticVirtualTextError = { fg = diag.error, bg = p.alert.critical.bg },
    DiagnosticVirtualTextWarn  = { fg = diag.warning, bg = p.alert.caution.bg },
    DiagnosticVirtualTextInfo  = { fg = diag.info, bg = p.alert.neutral.bg },
    DiagnosticVirtualTextHint  = { fg = diag.hint, bg = p.alert.good.bg },
    DiagnosticUnderlineError   = { undercurl = true, sp = diag.error },
    DiagnosticUnderlineWarn    = { undercurl = true, sp = diag.warning },
    DiagnosticUnderlineInfo    = { undercurl = true, sp = diag.info },
    DiagnosticUnderlineHint    = { undercurl = true, sp = diag.hint },
    DiagnosticUnnecessary      = { fg = syn.deprecated },
    DiagnosticDeprecated       = { fg = syn.deprecated, strikethrough = true },

    LspReferenceText           = { bg = ui.bg_p1 },
    LspReferenceRead           = { bg = ui.bg_p1 },
    LspReferenceWrite          = { bg = ui.bg_p1, underline = true },
    LspSignatureActiveParameter = { fg = syn.parameter, bold = true },
    LspInlayHint               = { fg = syn.deprecated, bg = ui.bg_m1, italic = true },
    LspCodeLens                = { fg = syn.comment, italic = true },
    LspInfoBorder              = { fg = ui.border, bg = ui.bg_p1 },

    ["@lsp.type.class"]         = { link = "@type" },
    ["@lsp.type.decorator"]     = { link = "@attribute" },
    ["@lsp.type.enum"]          = { link = "@type" },
    ["@lsp.type.enumMember"]    = { link = "@constant" },
    ["@lsp.type.interface"]     = { link = "@type" },
    ["@lsp.type.macro"]         = { link = "@function.macro" },
    ["@lsp.type.namespace"]     = { link = "@module" },
    ["@lsp.type.parameter"]     = { link = "@variable.parameter" },
    ["@lsp.type.property"]      = { link = "@property" },
    ["@lsp.type.struct"]        = { link = "@type" },
    ["@lsp.type.type"]          = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"]      = { link = "@variable" },
    ["@lsp.mod.deprecated"]     = { strikethrough = true },

    -- ===== nvim-cmp ==================================================
    CmpItemAbbr             = { fg = ui.pmenu.fg },
    CmpItemAbbrDeprecated   = { fg = syn.deprecated, strikethrough = true },
    CmpItemAbbrMatch        = { fg = syn.fun, bold = true },
    CmpItemAbbrMatchFuzzy   = { fg = syn.fun },
    CmpItemMenu             = { fg = ui.fg_dim },
    CmpItemKind             = { fg = syn.type },
    CmpItemKindText         = { fg = ui.fg },
    CmpItemKindMethod       = { fg = syn.fun },
    CmpItemKindFunction     = { fg = syn.fun },
    CmpItemKindConstructor  = { fg = syn.type },
    CmpItemKindField        = { fg = syn.identifier },
    CmpItemKindVariable     = { fg = syn.variable },
    CmpItemKindClass        = { fg = syn.type },
    CmpItemKindInterface    = { fg = syn.type },
    CmpItemKindModule       = { fg = syn.preproc },
    CmpItemKindProperty     = { fg = syn.identifier },
    CmpItemKindUnit         = { fg = syn.number },
    CmpItemKindValue        = { fg = syn.constant },
    CmpItemKindEnum         = { fg = syn.type },
    CmpItemKindKeyword      = { fg = syn.keyword },
    CmpItemKindSnippet      = { fg = syn.special1 },
    CmpItemKindColor        = { fg = syn.special2 },
    CmpItemKindFile         = { fg = syn.fun },
    CmpItemKindReference    = { fg = syn.special1 },
    CmpItemKindFolder       = { fg = syn.fun },
    CmpItemKindEnumMember   = { fg = syn.constant },
    CmpItemKindConstant     = { fg = syn.constant },
    CmpItemKindStruct       = { fg = syn.type },
    CmpItemKindEvent        = { fg = syn.special1 },
    CmpItemKindOperator     = { fg = syn.operator },
    CmpItemKindTypeParameter = { fg = syn.type },

    -- ===== Telescope =================================================
    -- Superfície de launcher: void-20, e a entrada selecionada em Ice, a
    -- mesma relação que o wofi tem.
    TelescopeNormal         = { fg = ui.fg, bg = ui.bg_p1 },
    TelescopeBorder         = { fg = ui.border, bg = ui.bg_p1 },
    TelescopeTitle          = { fg = syn.fun, bold = true },
    TelescopePromptNormal   = { fg = ui.fg, bg = ui.bg_p2 },
    TelescopePromptBorder   = { fg = ui.border, bg = ui.bg_p2 },
    TelescopePromptTitle    = { fg = p.bordeaux["300"], bold = true },
    TelescopePromptPrefix   = { fg = p.bordeaux["300"] },
    TelescopePromptCounter  = { fg = ui.fg_dim },
    TelescopeResultsNormal  = { fg = ui.fg, bg = ui.bg_p1 },
    TelescopeResultsBorder  = { fg = ui.border, bg = ui.bg_p1 },
    TelescopeResultsTitle   = { fg = ui.bg_p1, bg = ui.bg_p1 },
    TelescopePreviewNormal  = { fg = ui.fg, bg = ui.bg_m1 },
    TelescopePreviewBorder  = { fg = ui.border, bg = ui.bg_m1 },
    TelescopePreviewTitle   = { fg = diag.ok, bold = true },
    TelescopeSelection      = { fg = ui.pmenu.fg_sel, bg = ui.bg_visual },
    TelescopeSelectionCaret = { fg = p.bordeaux["300"], bg = ui.bg_visual },
    TelescopeMultiSelection = { fg = syn.special1 },
    TelescopeMatching       = { fg = syn.fun, bold = true },

    -- ===== neo-tree ==================================================
    NeoTreeNormal           = { fg = ui.fg, bg = ui.bg_m1 },
    NeoTreeNormalNC         = { fg = ui.fg_dim, bg = ui.bg_m1 },
    NeoTreeWinSeparator     = { fg = ui.border, bg = ui.bg_m1 },
    NeoTreeEndOfBuffer      = { fg = ui.bg_m1, bg = ui.bg_m1 },
    NeoTreeRootName         = { fg = syn.fun, bold = true },
    NeoTreeDirectoryName    = { fg = syn.fun },
    NeoTreeDirectoryIcon    = { fg = syn.fun },
    NeoTreeFileName         = { fg = ui.fg },
    NeoTreeFileIcon         = { fg = ui.fg_dim },
    NeoTreeFileNameOpened   = { fg = syn.special1 },
    NeoTreeIndentMarker     = { fg = ui.nontext },
    NeoTreeExpander         = { fg = ui.fg_dim },
    NeoTreeCursorLine       = { bg = ui.bg_p1 },
    NeoTreeTitleBar         = { fg = ui.bg, bg = syn.fun },
    NeoTreeGitAdded         = { fg = vcs.added },
    NeoTreeGitDeleted       = { fg = vcs.removed },
    NeoTreeGitModified      = { fg = vcs.changed },
    NeoTreeGitConflict      = { fg = diag.error, bold = true },
    NeoTreeGitUntracked     = { fg = syn.deprecated },
    NeoTreeGitIgnored       = { fg = syn.deprecated },
    NeoTreeSymbolicLinkTarget = { fg = syn.special1 },
    NeoTreeFloatBorder      = { fg = ui.border, bg = ui.bg_p1 },
    NeoTreeFloatTitle       = { fg = syn.fun, bg = ui.bg_p1, bold = true },

    -- ===== gitsigns ==================================================
    GitSignsAdd             = { fg = vcs.added, bg = bg },
    GitSignsChange          = { fg = vcs.changed, bg = bg },
    GitSignsDelete          = { fg = vcs.removed, bg = bg },
    GitSignsAddInline       = { bg = diff.add },
    GitSignsChangeInline    = { bg = diff.change },
    GitSignsDeleteInline    = { bg = diff.delete },
    GitSignsCurrentLineBlame = { fg = syn.comment, italic = true },

    -- ===== dashboard-nvim ============================================
    DashboardHeader         = { fg = p.bordeaux["300"] },
    DashboardFooter         = { fg = syn.comment, italic = true },
    DashboardDesc           = { fg = ui.fg },
    DashboardKey            = { fg = p.bordeaux["300"], bold = true },
    DashboardIcon           = { fg = syn.fun },
    DashboardShortCut       = { fg = syn.special1 },
    DashboardProjectTitle   = { fg = syn.fun, bold = true },
    DashboardProjectIcon    = { fg = syn.fun },
    DashboardMruTitle       = { fg = syn.fun, bold = true },
    DashboardMruIcon        = { fg = syn.fun },
    DashboardFiles          = { fg = ui.fg },

    -- ===== toggleterm ================================================
    -- Cobre a lacuna que o kanagawa deixava: o toggleterm herdava Normal e
    -- NormalFloat e nada mais.
    ToggleTerm1Normal       = { link = "Normal" },
    ToggleTerm1NormalFloat  = { link = "NormalFloat" },
    ToggleTerm1FloatBorder  = { link = "FloatBorder" },

    -- ===== lazy.nvim e mason =========================================
    -- Não são de uso diário, mas aparecem em toda atualização de plugin.
    LazyNormal              = { fg = ui.fg, bg = ui.bg_p1 },
    LazyH1                  = { fg = ui.bg, bg = p.bordeaux["300"], bold = true },
    LazyButton              = { fg = ui.fg, bg = ui.bg_p2 },
    LazyButtonActive        = { fg = ui.bg, bg = syn.fun, bold = true },
    LazyProgressDone        = { fg = diag.ok, bold = true },
    LazyProgressTodo        = { fg = ui.nontext },
    MasonNormal             = { fg = ui.fg, bg = ui.bg_p1 },
    MasonHeader             = { fg = ui.bg, bg = p.bordeaux["300"], bold = true },
    MasonHighlight          = { fg = syn.fun },
    MasonHighlightBlock     = { fg = ui.bg, bg = syn.fun },
    MasonMuted              = { fg = ui.fg_dim },
    MasonError              = { fg = diag.error },

    -- ===== Cobertura ==================================================
    -- Grupos encontrados comparando nossa lista com a do kanagawa, para não
    -- caírem no default do Neovim. É a contrapartida de ter tema próprio:
    -- ninguém cobre por baixo, então a lacuna precisa ser procurada. Quase
    -- tudo aqui é link para grupo que já definimos acima.

    -- Semantic tokens do LSP, que servidores emitem por linguagem.
    ["@lsp.type.const"]                    = { link = "@constant" },
    ["@lsp.type.comment"]                  = { link = "@comment" },
    ["@lsp.type.method"]                   = { link = "@function.method" },
    ["@lsp.type.decorator.rust"]           = { link = "@attribute" },
    ["@lsp.type.lifetime"]                 = { link = "@keyword.modifier" },
    ["@lsp.type.selfParameter"]            = { link = "@variable.builtin" },
    ["@lsp.type.builtinConstant"]          = { link = "@constant.builtin" },
    ["@lsp.type.magicFunction"]            = { link = "@function.builtin" },
    ["@lsp.type.bitwise"]                  = { link = "@operator" },
    ["@lsp.type.comparison"]               = { link = "@operator" },
    ["@lsp.type.punctuation"]              = { link = "@punctuation.delimiter" },
    ["@lsp.mod.readonly"]                  = { link = "@constant" },
    ["@lsp.mod.typeHint"]                  = { link = "@type" },
    ["@lsp.typemod.function.builtin"]      = { link = "@function.builtin" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.function.readonly"]     = { link = "@function" },
    ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.keyword.documentation"] = { link = "@keyword" },
    ["@lsp.typemod.operator.controlFlow"]  = { link = "@keyword" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.global"]       = { fg = syn.constant },
    ["@lsp.typemod.variable.static"]       = { fg = syn.constant },
    ["@lsp.typemod.variable.injected"]     = { link = "@variable" },

    ["@constructor.lua"]        = { link = "@punctuation.bracket" },
    ["@keyword.luap"]           = { link = "@string.regexp" },
    ["@keyword.modifier"]       = { fg = syn.keyword },
    ["@markup.environment"]     = { fg = syn.preproc },
    ["@string.special.symbol"]  = { fg = syn.constant },

    -- Janela de completion e de documentação do cmp, que são superfícies
    -- flutuantes próprias e não herdam Pmenu.
    CmpCompletion           = { link = "Pmenu" },
    CmpCompletionSel        = { link = "PmenuSel" },
    CmpCompletionBorder     = { fg = ui.border, bg = ui.pmenu.bg },
    CmpCompletionSbar       = { link = "PmenuSbar" },
    CmpCompletionThumb      = { link = "PmenuThumb" },
    CmpDocumentation        = { fg = ui.fg, bg = ui.bg_p1 },
    CmpDocumentationBorder  = { fg = ui.border, bg = ui.bg_p1 },
    CmpGhostText            = { fg = syn.deprecated, italic = true },
    CmpItemKindDefault      = { fg = ui.fg_dim },
    CmpItemKindCopilot      = { fg = diag.ok },

    -- Diagnósticos dentro de janela flutuante usam grupos próprios.
    DiagnosticFloatingError = { fg = diag.error, bg = ui.bg_p1 },
    DiagnosticFloatingWarn  = { fg = diag.warning, bg = ui.bg_p1 },
    DiagnosticFloatingInfo  = { fg = diag.info, bg = ui.bg_p1 },
    DiagnosticFloatingHint  = { fg = diag.hint, bg = ui.bg_p1 },
    DiagnosticFloatingOk    = { fg = diag.ok, bg = ui.bg_p1 },

    NeoTreeModified              = { fg = vcs.changed },
    NeoTreeGitStaged             = { fg = vcs.added },
    NeoTreeGitUnstaged           = { fg = vcs.changed },
    NeoTreeTabActive             = { fg = ui.fg, bg = ui.bg_p1, bold = true },
    NeoTreeTabInactive           = { fg = ui.fg_dim, bg = ui.bg_m1 },
    NeoTreeTabSeparatorActive    = { fg = ui.bg_p1, bg = ui.bg_p1 },
    NeoTreeTabSeparatorInactive  = { fg = ui.border, bg = ui.bg_m1 },

    DashboardCenter          = { fg = ui.fg },
    TelescopeResultsClass    = { fg = syn.type },
    TelescopeResultsStruct   = { fg = syn.type },
    TelescopeResultsField    = { fg = syn.identifier },
    TelescopeResultsMethod   = { fg = syn.fun },
    TelescopeResultsVariable = { fg = syn.variable },
  }
end

return M
